#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from urllib.request import urlopen
import sys
import re

# check arguments
if len(sys.argv) != 2:
    print('ERROR: An arXiv or inspire ID has to be given as argument')
    sys.exit(1)

id = sys.argv[1]
bibfile = 'references.bib'

# get bibtex from inspire
if '/' in id:
    query = 'eprint'
elif '.' in id:
    query = 'arxiv'
else:
    query = 'recid'
try:
    bibtex = urlopen(f'https://inspirehep.net/api/literature?q={query}%3A{id}&format=bibtex').read().decode()
except:
    print(f'ERROR: Query for {id} failed.')
    sys.exit(1)
if len(bibtex) == 0:
    print(f'ERROR: Could not get bibtex for {id}.')
    sys.exit(1)

# check whether the entry is already in references.bib
entry = re.compile('@[\w]*{([\S]*),').findall(bibtex)[0]
with open(bibfile) as bib:
    if entry in bib.read():
        print(f'ERROR: {bibfile} already contains the entry {entry}.')
        sys.exit(1)

# add bibtex to references.bib
with open(bibfile, 'a+') as bib:
    bib.write('\n' + bibtex)

print(f'Entry {entry} added to {bibfile} -> \\cite{{{entry}}}')
