#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from urllib.request import urlopen
import sys
import re

# check arguments
if len(sys.argv) != 2:
    print('ERROR: An arXiv or inspire ID has to be given as argument')
    sys.exit(1)

id = sys.argv[1]
bibfile = 'references.bib'

# convert arxiv to inspire ID
if '/' in id or '.' in id:
    if ':' in id:
        id = id[id.find(':')+1:]
    data = urlopen(f'http://inspirehep.net/search?p=find+eprint+{id}').read()
    match = re.compile(b'record/(\d*)').findall(data)
    if not match:
        print(f'ERROR: Could not get inspire ID for arXiv number {id}.')
        sys.exit(1)
    id = match[0].decode()

# get bibtex from inspire
data = urlopen(f'http://inspirehep.net/record/{id}/export/hx').read()
match = re.compile(b'[\S\s]*<pre>\n([\S\s]*)</pre>[\S\s]*').findall(data)
if not match:
    print(f'ERROR: Could not get bibtex for inspire ID {id}.')
    sys.exit(1)
bibtex = match[0].decode()

# check whether the entry is already in references.bib
entry = re.compile('@[\w]*{([\S]*),').findall(bibtex)[0]
with open(bibfile) as bib:
    if entry in bib.read():
        print(f'ERROR: {bibfile} already contains the entry {entry}.')
        sys.exit(1)

# add bibtex to references.bib
with open(bibfile, 'a+') as bib:
    bib.write('\n' + bibtex)

print(f'Entry {entry} added to {bibfile} -> \\cite{{{entry}}}')