#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: `basename $0` overleaf-git-url" 1>&2
  exit 1
fi

git config core.fileMode false
git config credential.helper store
git remote add overleaf $1
git pull overleaf master --allow-unrelated-histories
git push overleaf main:master
