#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import re
import subprocess

# check arguments
if len(sys.argv) != 2:
    print('ERROR: The tar file name has to be given as argument')
    sys.exit(1)

target = sys.argv[1]
base = os.path.splitext(target)[0]

# read file and remove comments at the beginning
def get_content(filename):
    with open(filename) as file:
        content = file.read()
        while content.startswith('% '):
            content = re.sub('^% .*\n', '', content)
        return content


# create paper.tex and paper-PRIVATE.tex with included content
paper = get_content(f'{base}.tex')
paper = paper.replace('\\begin{document}', '\\begin{document}\n\n\\vspace*{-3\\baselineskip}\n\\resizebox{!}{2cm}{\\includegraphics{belle2-logo.pdf}}')
private = None
if os.path.exists('authors-PRIVATE.tex'):
    private = get_content(f'{base}.tex')
for part in ['definitions', 'authors', 'title', 'abstract', 'pacs', 'body', 'acknowledgements', 'material']:
    print(part)
    content = get_content(f'{part}.tex')
    paper = paper.replace(f'\\input{{{part}}}', content)
    if private:
        if part == 'authors':
            content = get_content(f'{part}-PRIVATE.tex')
        private = private.replace(f'\\input{{{part}}}', content)

with open('paper.tex', 'w') as output:
    output.write(paper)
if private:
    with open('paper-PRIVATE.tex', 'w') as output:
        output.write(private)

# compile latex and make tarball
subprocess.run(['make', 'paper'])
if private:
    subprocess.run(['make', 'paper-PRIVATE'])
dependencies = {
    'prl': [],
    'prd': [],
    'jhep': ['jheppub.sty', 'JHEP.bst'],
    'epjc': ['svjour.cls', 'svepj.clo'],
}
files = ['paper.pdf', 'paper.tex', 'paper.bbl', 'references.bib', 'orcidlink.sty', 'definitions.tex', 'belle2-symbols.tex'] + dependencies.get(base, [])
if os.path.isdir('figures'):
    files.append('figures')
subprocess.run(['tar', 'czvf', 'arxiv.tgz'] + files)
if private and os.path.exists('authors.xml'):
    files += ['paper-PRIVATE.pdf', 'authors.xml']
    subprocess.run(['tar', 'czvf', 'journal.tgz'] + files)
