#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import re
import subprocess

# check arguments
if len(sys.argv) != 2:
    print('ERROR: The tar file name has to be given as argument')
    sys.exit(1)

target = sys.argv[1]
base = os.path.splitext(target)[0]

# read file and remove comments at the beginning
def get_content(filename):
    with open(filename) as file:
        content = file.read()
        while content.startswith('% '):
            content = re.sub('^% .*\n', '', content)
        return content


# create paper.tex with included content
paper = get_content(f'{base}.tex')
for part in ['definitions', 'authors', 'title', 'abstract', 'pacs', 'main', 'acknowledgements', 'material']:
    print(part)
    content = get_content(f'{part}.tex')
    paper = paper.replace(f'\\input{{{part}}}', content)

with open('paper.tex', 'w') as output:
    output.write(paper)

# compile latex and make tarball
subprocess.run(['make', 'paper'])
dependencies = {
    'prl': [],
    'prd': [],
    'jhep': ['jheppub.sty', 'JHEP.bst'],
    'epjc': ['svjour.cls', 'svepj.clo'],
}
files = ['paper.tex', 'paper.bbl', 'references.bib'] + dependencies.get(base, [])
if os.path.isdir('figures'):
    files.append('figures')
subprocess.run(['tar', 'czvf', 'paper.tgz'] + files)
